# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_zapbrew_global_optspecs
    string join \n debug q/quiet v/verbose prefix= cellar= caskroom= cache= repository= taps h/help V/version
end

function __fish_zapbrew_needs_command
    # Figure out if the current invocation already has a command.
    set -l cmd (commandline -opc)
    set -e cmd[1]
    argparse -s (__fish_zapbrew_global_optspecs) -- $cmd 2>/dev/null
    or return
    if set -q argv[1]
        # Also print the command, so this can be used to figure out what it is.
        echo $argv[1]
        return 1
    end
    return 0
end

function __fish_zapbrew_using_subcommand
    set -l cmd (__fish_zapbrew_needs_command)
    test -z "$cmd"
    and return 1
    contains -- $cmd[1] $argv
end

complete -c zapbrew -n "__fish_zapbrew_needs_command" -l prefix -d 'Print the install prefix, optionally for a formula. Resolved later' -r
complete -c zapbrew -n "__fish_zapbrew_needs_command" -l cellar -d 'Print the Cellar path, optionally for a formula. Resolved later' -r
complete -c zapbrew -n "__fish_zapbrew_needs_command" -l caskroom -d 'Print the Caskroom path, optionally for a cask token. Resolved later' -r
complete -c zapbrew -n "__fish_zapbrew_needs_command" -l cache -d 'Print the download cache path, optionally for a formula. Resolved later' -r
complete -c zapbrew -n "__fish_zapbrew_needs_command" -l repository -d 'Print the repository path, optionally for a tap. Resolved later' -r
complete -c zapbrew -n "__fish_zapbrew_needs_command" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -l taps -d 'Print the Taps directory path'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -s V -l version -d 'Print version'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "install" -d 'Install formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "reinstall" -d 'Reinstall formulae'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "uninstall" -d 'Uninstall formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "upgrade" -d 'Upgrade outdated formulae'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "outdated" -d 'List outdated formulae and casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "list" -d 'List installed formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "info" -d 'Show information about formulae and casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "deps" -d 'Show dependencies of formulae'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "uses" -d 'Show formulae and casks that depend on the named formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "leaves" -d 'List installed formulae not required by others'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "autoremove" -d 'Uninstall formulae that are no longer needed'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "pin" -d 'Pin formulae, preventing upgrades'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "unpin" -d 'Unpin formulae, allowing upgrades'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "link" -d 'Symlink a keg\'s files into the prefix'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "unlink" -d 'Remove a keg\'s symlinks from the prefix'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "fetch" -d 'Download bottles without installing'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "cleanup" -d 'Remove stale downloads and old versions'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "search" -d 'Search for formulae and casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "desc" -d 'Show descriptions or search names/descriptions of formulae/casks'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "postinstall" -d 'Rerun post-install steps for installed formulae'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "config" -d 'Show the effective configuration'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "shellenv" -d 'Print shell integration for the environment'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "tap" -d 'Tap a formula repository, or list taps'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "untap" -d 'Remove a tapped repository'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "tap-info" -d 'Show information about a tap'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "doctor" -d 'Check the system for potential problems'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "services" -d 'Manage background services'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "update" -d 'Fetch the latest catalog and taps'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "shim" -d 'Manage the opt-in `brew` shim'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "completions" -d 'Manage shell completion links'
complete -c zapbrew -n "__fish_zapbrew_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l appdir -d 'Target application directory for cask apps' -r -F
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l only-dependencies -d 'Install only the dependencies, not the formulae themselves'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -s f -l force -d 'Install even if already installed'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -s n -l dry-run -d 'Show what would be installed without doing it'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l build-from-source -d 'Compile from source instead of pouring a bottle'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l HEAD -d 'Install the HEAD version'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -s i -l interactive -d 'Run the installation interactively'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l include-test -d 'Include test dependencies during expansion'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l cask -d 'Treat the named arguments as casks (macOS only)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l formula -d 'Treat the named arguments as formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand install" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand reinstall" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand reinstall" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand reinstall" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand reinstall" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -s f -l force -d 'Delete all installed versions, not just the active one'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -l ignore-dependencies -d 'Do not check for dependents before uninstalling'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -l cask -d 'Treat the named arguments as casks (macOS only)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -l formula -d 'Treat the named arguments as formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -l zap -d 'Also remove all files a cask created (cask only)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uninstall" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand upgrade" -s n -l dry-run -d 'Show what would be upgraded without doing it'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand upgrade" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand upgrade" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand upgrade" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand upgrade" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -l json -d 'Emit JSON output (v2 schema)' -r -f -a "v2\t''"
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -l greedy -d 'Include casks with auto-updates or `latest` versions'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -l greedy-latest -d 'Include casks whose version is `latest`'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -l greedy-auto-updates -d 'Include casks that update themselves'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand outdated" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -l versions -d 'Show version numbers'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -s 1 -d 'Print one entry per line'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -l cask -d 'List casks instead of formulae (macOS only)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -l formula -d 'Treat the named arguments as formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand list" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand info" -l json -d 'Emit JSON output (v2 schema)' -r -f -a "v2\t''"
complete -c zapbrew -n "__fish_zapbrew_using_subcommand info" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand info" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand info" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand info" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -l tree -d 'Render the dependency graph as a tree'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -l union -d 'Show the union of dependencies across all arguments'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -l include-build -d 'Include `:build` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -l include-test -d 'Include `:test` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -l include-optional -d 'Include `:optional` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -l skip-recommended -d 'Skip `:recommended` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand deps" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -s r -l recursive -d 'Resolve the reverse-dependency closure recursively'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -l installed -d 'Restrict results to installed formulae and casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -l include-build -d 'Include `:build` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -l include-test -d 'Include `:test` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -l include-optional -d 'Include `:optional` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -l skip-recommended -d 'Skip `:recommended` dependencies'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand uses" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand leaves" -s r -l installed-on-request -d 'Only list formulae installed on request'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand leaves" -s p -l installed-as-dependency -d 'Only list formulae installed as a dependency'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand leaves" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand leaves" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand leaves" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand leaves" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand autoremove" -s n -l dry-run -d 'Show what would be removed without doing it'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand autoremove" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand autoremove" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand autoremove" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand autoremove" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand pin" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand pin" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand pin" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand pin" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unpin" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unpin" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unpin" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unpin" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand link" -l overwrite -d 'Delete files that already exist in the prefix'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand link" -s n -l dry-run -d 'Show what would be linked without doing it'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand link" -s f -l force -d 'Force linking even for keg-only formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand link" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand link" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand link" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand link" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unlink" -s n -l dry-run -d 'Show what would be removed without doing it'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unlink" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unlink" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unlink" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand unlink" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand fetch" -l deps -d 'Also fetch the dependency closure'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand fetch" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand fetch" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand fetch" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand fetch" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -l prune -d 'Remove all cache files older than <days>, or \'all\'' -r
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -s s -l scrub -d 'Scrub the download cache of the latest versions too'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -s n -l dry-run -d 'Show what would be removed without doing it'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -l prune-prefix -d 'Only prune the symlinks and directories from the prefix'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand cleanup" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand search" -l desc -d 'Search descriptions as well as names'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand search" -l formula -d 'Restrict the search to formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand search" -l cask -d 'Restrict the search to casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand search" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand search" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand search" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand search" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -s s -l search -d 'Search names and descriptions for <text>' -r
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -s n -l search-name -d 'Search only names' -r
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -s d -l search-description -d 'Search only descriptions' -r
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -l formula -d 'Treat named arguments as formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -l cask -d 'Treat named arguments as casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand desc" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand postinstall" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand postinstall" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand postinstall" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand postinstall" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand config" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand config" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand config" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand config" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shellenv" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shellenv" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shellenv" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shellenv" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap" -s f -l force -d 'Force the tap even for a built-in name'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand untap" -s f -l force -d 'Remove even if formulae from the tap are installed'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand untap" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand untap" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand untap" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand untap" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap-info" -l installed -d 'Show information for every installed tap'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap-info" -l json -d 'Emit JSON output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap-info" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap-info" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap-info" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand tap-info" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand doctor" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand doctor" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand doctor" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand doctor" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "list" -d 'List services and their status'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "start" -d 'Start services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "stop" -d 'Stop services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "restart" -d 'Restart services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "run" -d 'Run a service without registering it to launch at login or boot'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "info" -d 'Print one-line status for services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "kill" -d 'Stop a service but keep it registered'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "cleanup" -d 'Remove unused service files'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and not __fish_seen_subcommand_from list start stop restart run info kill cleanup help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from list" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from list" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from start" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from start" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from start" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from start" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from stop" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from stop" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from stop" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from restart" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from restart" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from restart" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from restart" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from run" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from run" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from run" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from run" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from info" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from info" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from info" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from kill" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from kill" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from kill" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from kill" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from cleanup" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from cleanup" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from cleanup" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from cleanup" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "list" -d 'List services and their status'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "start" -d 'Start services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "stop" -d 'Stop services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "restart" -d 'Restart services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "run" -d 'Run a service without registering it to launch at login or boot'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "info" -d 'Print one-line status for services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "kill" -d 'Stop a service but keep it registered'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "cleanup" -d 'Remove unused service files'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand services; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand update" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand update" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand update" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand update" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and not __fish_seen_subcommand_from install remove help" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and not __fish_seen_subcommand_from install remove help" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and not __fish_seen_subcommand_from install remove help" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and not __fish_seen_subcommand_from install remove help" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and not __fish_seen_subcommand_from install remove help" -f -a "install" -d 'Install the `<prefix>/bin/brew` shim'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and not __fish_seen_subcommand_from install remove help" -f -a "remove" -d 'Remove the `<prefix>/bin/brew` shim'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and not __fish_seen_subcommand_from install remove help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from install" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from install" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from install" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from remove" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from remove" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from remove" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from help" -f -a "install" -d 'Install the `<prefix>/bin/brew` shim'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove the `<prefix>/bin/brew` shim'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand shim; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -a "state" -d 'Display the current completion link state'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -a "link" -d 'Link discovered completion files into the active prefix'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -a "unlink" -d 'Remove only links to discovered completion files'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -a "generate" -d 'Generate a completion script from the live Clap surface'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and not __fish_seen_subcommand_from state link unlink generate help" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from state" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from state" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from state" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from state" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from link" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from link" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from link" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from link" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from unlink" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from unlink" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from unlink" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from unlink" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from generate" -l debug -d 'Enable debug output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from generate" -s q -l quiet -d 'Suppress non-essential output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from generate" -s v -l verbose -d 'Enable verbose output'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from generate" -s h -l help -d 'Print help'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from help" -f -a "state" -d 'Display the current completion link state'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from help" -f -a "link" -d 'Link discovered completion files into the active prefix'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from help" -f -a "unlink" -d 'Remove only links to discovered completion files'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from help" -f -a "generate" -d 'Generate a completion script from the live Clap surface'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand completions; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "install" -d 'Install formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "reinstall" -d 'Reinstall formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "uninstall" -d 'Uninstall formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "upgrade" -d 'Upgrade outdated formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "outdated" -d 'List outdated formulae and casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "list" -d 'List installed formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "info" -d 'Show information about formulae and casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "deps" -d 'Show dependencies of formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "uses" -d 'Show formulae and casks that depend on the named formulae or casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "leaves" -d 'List installed formulae not required by others'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "autoremove" -d 'Uninstall formulae that are no longer needed'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "pin" -d 'Pin formulae, preventing upgrades'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "unpin" -d 'Unpin formulae, allowing upgrades'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "link" -d 'Symlink a keg\'s files into the prefix'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "unlink" -d 'Remove a keg\'s symlinks from the prefix'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "fetch" -d 'Download bottles without installing'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "cleanup" -d 'Remove stale downloads and old versions'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "search" -d 'Search for formulae and casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "desc" -d 'Show descriptions or search names/descriptions of formulae/casks'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "postinstall" -d 'Rerun post-install steps for installed formulae'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "config" -d 'Show the effective configuration'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "shellenv" -d 'Print shell integration for the environment'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "tap" -d 'Tap a formula repository, or list taps'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "untap" -d 'Remove a tapped repository'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "tap-info" -d 'Show information about a tap'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "doctor" -d 'Check the system for potential problems'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "services" -d 'Manage background services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "update" -d 'Fetch the latest catalog and taps'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "shim" -d 'Manage the opt-in `brew` shim'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "completions" -d 'Manage shell completion links'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and not __fish_seen_subcommand_from install reinstall uninstall upgrade outdated list info deps uses leaves autoremove pin unpin link unlink fetch cleanup search desc postinstall config shellenv tap untap tap-info doctor services update shim completions help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "list" -d 'List services and their status'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "start" -d 'Start services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "stop" -d 'Stop services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "restart" -d 'Restart services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "run" -d 'Run a service without registering it to launch at login or boot'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "info" -d 'Print one-line status for services'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "kill" -d 'Stop a service but keep it registered'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from services" -f -a "cleanup" -d 'Remove unused service files'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from shim" -f -a "install" -d 'Install the `<prefix>/bin/brew` shim'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from shim" -f -a "remove" -d 'Remove the `<prefix>/bin/brew` shim'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from completions" -f -a "state" -d 'Display the current completion link state'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from completions" -f -a "link" -d 'Link discovered completion files into the active prefix'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from completions" -f -a "unlink" -d 'Remove only links to discovered completion files'
complete -c zapbrew -n "__fish_zapbrew_using_subcommand help; and __fish_seen_subcommand_from completions" -f -a "generate" -d 'Generate a completion script from the live Clap surface'
