//! Integration tests for the preferred-GCC `ld.so.conf` snippet
//! (`setup_preferred_gcc_libs`), mirroring brew's
//! `extend/os/linux/install.rb#setup_preferred_gcc_libs`.

use std::collections::HashMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;

use camino::Utf8PathBuf;
use tempfile::TempDir;
use zapbrew_prefix::{
    Env, EnvDetectInput, PrefixError, SystemCommandRunner, setup_preferred_gcc_libs,
};

/// Build a Linux `Env` rooted at `prefix` (mirrors `detect_prefix_env` in
/// path.rs).
fn linux_env(prefix: &camino::Utf8Path) -> Env {
    let input = EnvDetectInput {
        os: "linux".to_owned(),
        arch: "x86_64".to_owned(),
        home: prefix.to_path_buf(),
        xdg_cache_home: None,
        vars: HashMap::from([
            ("HOMEBREW_PREFIX".to_owned(), prefix.to_string()),
            (
                "HOMEBREW_CELLAR".to_owned(),
                prefix.join("Cellar").to_string(),
            ),
            ("HOMEBREW_TEMP".to_owned(), prefix.join("tmp").to_string()),
        ]),
        available_parallelism: 2,
    };
    match Env::detect_from(&input, &SystemCommandRunner) {
        Ok(env) => env,
        Err(err) => panic!("detect env: {err}"),
    }
}

fn utf8_temp() -> (TempDir, Utf8PathBuf) {
    let temp = match TempDir::new() {
        Ok(temp) => temp,
        Err(err) => panic!("tempdir: {err}"),
    };
    let root = match Utf8PathBuf::from_path_buf(temp.path().to_path_buf()) {
        Ok(root) => root,
        Err(path) => panic!("non-utf8 temp path {}", path.display()),
    };
    (temp, root)
}

fn create_dir(path: &camino::Utf8Path) {
    if let Err(err) = fs::create_dir_all(path.as_std_path()) {
        panic!("create {}: {err}", path);
    }
}

fn write_file(path: &camino::Utf8Path, bytes: &[u8]) {
    if let Some(parent) = path.parent() {
        create_dir(parent);
    }
    if let Err(err) = fs::write(path.as_std_path(), bytes) {
        panic!("write {}: {err}", path);
    }
}

/// Make a brewed GCC opt prefix readable at `<prefix>/opt/gcc`.
fn plant_brewed_gcc(prefix: &camino::Utf8Path) {
    create_dir(&prefix.join("opt/gcc/lib/gcc/current"));
}

/// Make a brewed glibc marker readable at `<prefix>/opt/glibc/bin/ld.so`.
fn plant_brewed_glibc(prefix: &camino::Utf8Path) {
    write_file(&prefix.join("opt/glibc/bin/ld.so"), b"#!/bin/sh\n");
}

fn conf_path(prefix: &camino::Utf8Path) -> camino::Utf8PathBuf {
    prefix.join("etc/ld.so.conf.d/50-homebrew-preferred-gcc.conf")
}

fn expected_content(prefix: &camino::Utf8Path) -> String {
    format!(
        "# This file is generated by Homebrew. Do not modify.\n{}/opt/gcc/lib/gcc/current\n",
        prefix
    )
}

#[test]
fn writes_conf_snippet_when_glibc_and_gcc_present() {
    let (_temp, root) = utf8_temp();
    let prefix = root.join("prefix");
    plant_brewed_gcc(&prefix);
    plant_brewed_glibc(&prefix);
    let env = linux_env(&prefix);

    setup_preferred_gcc_libs(&env).expect("setup on linux with glibc+gcc");

    let conf = conf_path(&prefix);
    let content = match fs::read_to_string(conf.as_std_path()) {
        Ok(content) => content,
        Err(err) => panic!("read conf {conf}: {err}"),
    };
    assert_eq!(
        content,
        expected_content(&prefix),
        "conf content must match brew"
    );

    // The conf directory must be group/other write-stripped (brew `go-w`).
    let dir = prefix.join("etc/ld.so.conf.d");
    let mode = fs::metadata(dir.as_std_path())
        .expect("stat conf.d")
        .permissions()
        .mode()
        & 0o777;
    assert_eq!(mode & 0o022, 0, "conf.d must not be group/other writable");
}

#[test]
fn is_idempotent_when_content_unchanged() {
    let (_temp, root) = utf8_temp();
    let prefix = root.join("prefix");
    plant_brewed_gcc(&prefix);
    plant_brewed_glibc(&prefix);
    let env = linux_env(&prefix);

    setup_preferred_gcc_libs(&env).expect("first setup");
    let conf = conf_path(&prefix);
    let before = fs::metadata(conf.as_std_path())
        .expect("stat conf")
        .modified()
        .expect("modified time");
    // A second run must not rewrite the file (content is identical).
    setup_preferred_gcc_libs(&env).expect("second setup");
    let after = fs::metadata(conf.as_std_path())
        .expect("stat conf")
        .modified()
        .expect("modified time");
    assert_eq!(before, after, "idempotent run must not rewrite the conf");
    let content = fs::read_to_string(conf.as_std_path()).expect("read conf");
    assert_eq!(content, expected_content(&prefix));
}

#[test]
fn rewrites_when_content_drifts() {
    let (_temp, root) = utf8_temp();
    let prefix = root.join("prefix");
    plant_brewed_gcc(&prefix);
    plant_brewed_glibc(&prefix);
    let env = linux_env(&prefix);

    // Pre-seed a stale conf with wrong content.
    let conf = conf_path(&prefix);
    write_file(&conf, b"stale\n");
    setup_preferred_gcc_libs(&env).expect("setup over stale conf");
    let content = fs::read_to_string(conf.as_std_path()).expect("read conf");
    assert_eq!(
        content,
        expected_content(&prefix),
        "stale conf must be replaced"
    );
}

#[test]
fn noop_without_brewed_gcc() {
    let (_temp, root) = utf8_temp();
    let prefix = root.join("prefix");
    // Only glibc, no gcc opt prefix.
    plant_brewed_glibc(&prefix);
    let env = linux_env(&prefix);

    setup_preferred_gcc_libs(&env).expect("setup without gcc");
    assert!(!conf_path(&prefix).exists(), "no conf without brewed gcc");
}

#[test]
fn noop_without_brewed_glibc() {
    let (_temp, root) = utf8_temp();
    let prefix = root.join("prefix");
    // Only gcc, no glibc.
    plant_brewed_gcc(&prefix);
    let env = linux_env(&prefix);

    setup_preferred_gcc_libs(&env).expect("setup without glibc");
    assert!(!conf_path(&prefix).exists(), "no conf without brewed glibc");
}

#[test]
fn noop_on_macos() {
    use std::os::unix::process::ExitStatusExt;
    use std::sync::Mutex;
    use zapbrew_prefix::{CommandOutput, CommandRunner, CommandSpec};

    struct SwVersRunner {
        records: Mutex<usize>,
    }
    impl CommandRunner for SwVersRunner {
        fn run(&self, _spec: &CommandSpec) -> Result<CommandOutput, std::io::Error> {
            *self.records.lock().expect("records") += 1;
            Ok(CommandOutput::new(
                std::process::ExitStatus::from_raw(0),
                b"15.0\n".to_vec(),
                Vec::new(),
            ))
        }
    }
    let runner = SwVersRunner {
        records: Mutex::new(0),
    };

    let (_temp, root) = utf8_temp();
    let prefix = root.join("prefix");
    plant_brewed_gcc(&prefix);
    plant_brewed_glibc(&prefix);
    let input = EnvDetectInput {
        os: "macos".to_owned(),
        arch: "arm64".to_owned(),
        home: prefix.to_path_buf(),
        xdg_cache_home: None,
        vars: HashMap::from([
            ("HOMEBREW_PREFIX".to_owned(), prefix.to_string()),
            (
                "HOMEBREW_CELLAR".to_owned(),
                prefix.join("Cellar").to_string(),
            ),
            ("HOMEBREW_TEMP".to_owned(), prefix.join("tmp").to_string()),
        ]),
        available_parallelism: 2,
    };
    let env = match Env::detect_from(&input, &runner) {
        Ok(env) => env,
        Err(err) => panic!("detect env: {err}"),
    };
    match setup_preferred_gcc_libs(&env) {
        Ok(()) => {}
        Err(err) => panic!("macOS setup: {err}"),
    }
    assert!(
        !conf_path(&prefix).exists(),
        "macOS must not write a Linux ld.so.conf snippet"
    );
}

#[test]
fn does_not_panic_or_error_on_empty_prefix() {
    let (_temp, root) = utf8_temp();
    let prefix = root.join("prefix");
    let env = linux_env(&prefix);
    // No gcc, no glibc — must be a clean no-op, not an error.
    match setup_preferred_gcc_libs(&env) {
        Ok(()) => {}
        Err(PrefixError::NoSystemLdSo) => return,
        Err(err) => panic!("empty prefix setup: {err}"),
    }
    assert!(!conf_path(&prefix).exists());
}
